stages:
  - nonfree

init:
  stage: nonfree
  script:
    - git clone git@iis-git.ee.ethz.ch:pulp-restricted/cva6-nonfree.git nonfree
    - cd nonfree && git checkout e0cc6f1406ddb0d2e212fccd932aafe40510a44f
  artifacts:
    paths: [ nonfree/ci.yml ]

subpipe:
  stage: nonfree
  needs: [ init ]
  trigger:
    include:
      - artifact: nonfree/ci.yml
        job: init
    strategy: depend
