stages:
  - nonfree

init:
  stage: nonfree
  script:
    - git clone git@iis-git.ee.ethz.ch:pulp-restricted/cva6-nonfree.git nonfree
    - cd nonfree && git checkout 49f10b91d89d964e7516d992a5fc4ef035ed5057
  artifacts:
    paths: [ nonfree/ci.yml ]

subpipe:
  stage: nonfree
  needs: [ init ]
  trigger:
    include:
      - artifact: nonfree/ci.yml
        job: init
    strategy: depend
