stages:
  - nonfree

init:
  stage: nonfree
  script:
    - git clone git@iis-git.ee.ethz.ch:pulp-restricted/cva6-nonfree.git nonfree
    - cd nonfree && git checkout 868699ecf3ac05a2635599c6bd69cf0b8975974c
  artifacts:
    paths: [ nonfree/ci.yml ]

subpipe:
  stage: nonfree
  needs: [ init ]
  trigger:
    include:
      - artifact: nonfree/ci.yml
        job: init
    strategy: depend
